### ISSUE TITLE
Проблемы с документацией по курсу

### ISSUE THREAD

**Issue by AlKoAl** [edosedgar/stm32f0_ARM#17]
Добрый день. 
Есть определённая проблема в материалах к курсу. Задание 05 "nvic" по какой-то причине не содержит в себе никакой текстовой информации: файл Readme.md представлен одной строкой. Можете ли вы исправить данный баг, пожалуйста?

**Comment by edosedgar** [comment]
Добрый день, спасибо за замечение. Код к лабе написан, отсутствует лишь должное описание. Если у вас есть желание добавить описание, свяжитесь со мной.
